[package]
name = "dr-downloader"
version = "0.1.0"
authors = ["Frederik P. B. H. <frepbh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
async-recursion = "0.3.2"
reqwest = "*"
serde_json = "1.0.*"
