name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
    - uses: Swatinem/rust-cache@v1.2.0
    
    - name: Build
      run: cargo +nightly build --verbose --release
    
    - name: Run tests
      run: cargo +nightly test --verbose
      
    - name: Upload binary
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ${{ github.event.repository.name }}
        path: ./target/release/${{ github.event.repository.name }}.exe
        if-no-files-found: error
